# Generated by Django 4.1.7 on 2023-03-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_color_product_color_quantity_product_gpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(null=True, verbose_name='Цена'),
        ),
    ]
